[package]
name = "pawos"
version = "0.1.0"
authors = ["Paweł Trojański <pawel.trojanski@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bootloader = "0.9.11"
volatile = "0.2.6"